version: "3.8"

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.492.2-lts-jdk17
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    user: root
    restart: always
    ports:
      - "50000:50000"
      - "8010:8080"
    volumes:
      - jenkins:/var/jenkins_home

volumes:
  jenkins:
    driver: local